# Generated by Django 5.2.4 on 2025-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryname',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='id',
        ),
        migrations.AddField(
            model_name='categoryname',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
