# Generated by Django 5.2.4 on 2025-07-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_buyer_created_by_alter_buyer_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_detail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
