# Generated by Django 5.2.4 on 2025-07-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerregistration',
            name='buyer_image',
            field=models.ImageField(null=True, upload_to='buyers/'),
        ),
    ]
