# Generated by Django 5.2.4 on 2025-07-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_address',
            field=models.TextField(default='this is default address'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_contact',
            field=models.CharField(default='this is default mobile number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking'), ('UPI', 'UPI')], max_length=20),
        ),
    ]
