# Generated by Django 5.2.4 on 2025-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_orderitem_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_contact',
            field=models.CharField(),
        ),
    ]
